#!/usr/bin/env bash
# transfer file from client to remote server
# takes 4 parameter:
#	path_to_file
#	IP
#	username
#	path to ssh_identity_file

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

path_to_file=$1
IP=$2
username=$3
ssh_identity_file=$4

scp -o "StrictHostKeyChecking=no" -i "$ssh_identity_file" "$path_to_file" "${username}@${IP}:~/"
