#!/usr/bin/env bash
# install and configure nginx on web server

sudo apt-get update
sudo apt-get -y install nginx # install nginx

# change file ownwership to current user
sudo chown -R $USER:$USER /var/www/html
# update html doc
echo "Hello World!"  > /var/www/html/index.nginx-debian.html

# check for error
sudo nginx -t
#restart nginx
sudo service nginx restart
