#!/usr/bin/env bash
# install and configure nginx on web server


nginx_config="/etc/nginx/sites-available/default"
new_content="\tlocation /redirect_me {\n\t\treturn 301 http://new-destination.com;\n\t}"


sudo apt-get update
sudo apt-get -y install nginx # install nginx

# change file owner
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" "$nginx_config"

# update html doc
echo "Hello World!"  > /var/www/html/index.nginx-debian.html
# shellcheck disable=SC1003
sudo sed -i -e '/^server {/,/^}/{/^}/i\'"$new_content" -e '}' "$nginx_config"

# check for error
sudo nginx -t
#restart nginx
sudo service nginx restart
