#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process

filename="/tmp/my_process"

echo $$ > "/var/run/my_process.pid"
trap 'exit' TERM

while true
do 
	echo "I am alive!" >> $filename
	sleep 2s
done
