#!/usr/bin/env bash
# display hours and minutes from 0hr to 12 hrs

hour=0
while [ "$hour" -le 12 ]; do
	echo "Hour:" $hour
	minute=1
	while [ "$minute" -le 59 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
