#!/usr/bin/env bash
# configures an Ubuntu server, assign IP address

host_file="/etc/hosts"
new_hostfile="hosts.new"

cp "$host_file" "$new_hostfile"  &&
sed -i '0,/127.0.0.1/s//127.0.0.2/' "$new_hostfile"

echo -e "\n# == configure custom domain servers ==\n\
127.0.0.2\tlocalhost\n\
8.8.8.8\t\tfacebook.com\n" >> "$new_hostfile"

sudo cp -f "hosts.new" "$host_file"
